[package]
name = "bufferstats"
edition = "2021"
version = "0.1.3"
description = "A library for calculating statistics on buffer data"
repository = "https://github.com/delion264/bufferstats"
license-file = "LICENSE"
